# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('sell_currency', models.CharField(max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buy_currency', models.CharField(max_length=3)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date_booked', models.DateTimeField(editable=False)),
            ],
        ),
    ]
