# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
