# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20170314_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
