# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20170315_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='rate',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
